# Generated by Django 3.0.4 on 2020-03-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0004_auto_20200321_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmemberrole',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
