# Generated by Django 3.0.4 on 2020-03-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0008_remove_projectuser_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='finished',
        ),
        migrations.AddField(
            model_name='project',
            name='documentation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
