# Generated by Django 3.0.4 on 2020-03-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0017_auto_20200329_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
    ]
