# Generated by Django 3.0.4 on 2020-03-29 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0019_auto_20200329_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='business_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
