# Generated by Django 3.0.4 on 2020-03-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0020_auto_20200329_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storytest',
            old_name='project',
            new_name='story',
        ),
    ]
