# Generated by Django 3.0.4 on 2020-04-09 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0026_auto_20200401_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AddField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(related_name='developers', to='smrpo.ProjectUser'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='smrpo.ProjectUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='scrum_master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scrum_master', to='smrpo.ProjectUser'),
            preserve_default=False,
        ),
    ]
