# Generated by Django 3.0.4 on 2020-04-11 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0030_auto_20200409_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='sprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='smrpo.Sprint'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together=set(),
        ),
    ]
