# Generated by Django 3.0.4 on 2020-04-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0031_auto_20200411_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='realized',
            field=models.BooleanField(default=False),
        ),
    ]
