# Generated by Django 3.0.4 on 2020-04-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0032_story_realized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='smrpo.Sprint'),
        ),
    ]
