# Generated by Django 3.0.4 on 2020-04-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0035_task_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='time_complexity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
