# Generated by Django 3.0.4 on 2020-04-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='all_tasks_finished',
        ),
    ]
