# Generated by Django 3.0.4 on 2020-05-04 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0002_remove_story_all_tasks_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='business_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
