# Generated by Django 3.0.4 on 2020-05-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0004_story_unique_by_project_count_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='unique_by_project_count_id',
            field=models.IntegerField(blank=True),
        ),
    ]
