# Generated by Django 3.0.4 on 2020-04-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0004_auto_20200416_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectUser',
        ),
    ]
