# Generated by Django 3.0.4 on 2020-04-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0005_delete_projectuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='all_tasks_finished',
            field=models.BooleanField(default=False),
        ),
    ]
