# Generated by Django 3.0.4 on 2020-03-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0006_auto_20200322_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectuserrole',
            old_name='role',
            new_name='title',
        ),
    ]
