# Generated by Django 3.0.4 on 2020-04-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0006_story_all_tasks_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='rejection_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
