# Generated by Django 3.0.4 on 2020-04-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0009_remove_task_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
