# Generated by Django 3.0.4 on 2020-05-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0010_worksession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksession',
            options={'ordering': ('start',)},
        ),
        migrations.RemoveField(
            model_name='task',
            name='active',
        ),
    ]
