# Generated by Django 3.0.4 on 2020-03-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0010_auto_20200323_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuserrole',
            name='title',
        ),
    ]
