# Generated by Django 3.0.4 on 2020-04-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0010_auto_20200418_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='users',
        ),
    ]
