# Generated by Django 3.0.4 on 2020-05-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0011_auto_20200520_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='total_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='worksession',
            unique_together={('task', 'user')},
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='end',
        ),
    ]
