# Generated by Django 3.0.4 on 2020-04-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0007_auto_20200418_1653'),
        ('smrpo', '0012_auto_20200418_1916'),
    ]

    operations = [
    ]
