# Generated by Django 3.0.4 on 2020-04-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0012_auto_20200418_1916'),
        ('smrpo', '0009_auto_20200418_1740'),
    ]

    operations = [
    ]
