# Generated by Django 3.0.4 on 2020-03-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0012_auto_20200323_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuserrole',
            name='title',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
