# Generated by Django 3.0.4 on 2020-04-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0013_merge_20200418_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
    ]
