# Generated by Django 3.0.4 on 2020-05-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0013_auto_20200520_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksession',
            options={'ordering': ('date',)},
        ),
        migrations.RenameField(
            model_name='worksession',
            old_name='start',
            new_name='date',
        ),
        migrations.AddField(
            model_name='worksession',
            name='active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
