# Generated by Django 3.0.4 on 2020-05-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0014_auto_20200520_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='date',
            field=models.DateField(),
        ),
    ]
