# Generated by Django 3.0.4 on 2020-04-18 18:07

from django.db import migrations, models
import smrpo.models.task


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0014_auto_20200418_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.FloatField(default=1.5, validators=[smrpo.models.task.higher_than_zero]),
            preserve_default=False,
        ),
    ]
