# Generated by Django 3.0.4 on 2020-05-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0015_auto_20200520_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='estimated_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
