# Generated by Django 3.0.4 on 2020-05-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0016_worksession_estimated_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='assigned_new_sprint',
            field=models.BooleanField(default=False),
        ),
    ]
