# Generated by Django 3.0.4 on 2020-04-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0016_task_assignee_awaiting'),
        ('smrpo', '0013_merge_20200418_1942'),
    ]

    operations = [
    ]
