# Generated by Django 3.0.4 on 2020-03-29 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0016_sprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('business_value', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_stories', to='smrpo.ProjectUser')),
            ],
        ),
        migrations.CreateModel(
            name='StoryPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smrpo.Story')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smrpo.StoryPriority'),
        ),
        migrations.AddField(
            model_name='story',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='smrpo.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='story',
            unique_together={('name', 'project')},
        ),
    ]
