# Generated by Django 3.0.4 on 2020-03-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0018_auto_20200329_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storypriority',
            options={'verbose_name_plural': 'Story priorities'},
        ),
    ]
