# Generated by Django 3.0.4 on 2020-03-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0021_auto_20200329_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storytest',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='smrpo.Story'),
        ),
    ]
