# Generated by Django 3.0.4 on 2020-04-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0024_auto_20200401_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='smrpo.Project'),
        ),
    ]
