# Generated by Django 3.0.4 on 2020-04-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0029_auto_20200409_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='product_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_owner', to='smrpo.ProjectUser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scrum_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrum_master', to='smrpo.ProjectUser'),
        ),
    ]
