# Generated by Django 3.0.4 on 2020-04-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smrpo', '0033_auto_20200411_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='smrpo.Story'),
            preserve_default=False,
        ),
    ]
